name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Decode and inspect GPG key
        env:
          PRIVATE_GPG_KEY: ${{ secrets.PRIVATE_GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          echo "$PRIVATE_GPG_KEY" | base64 --decode > private.key
      
          echo "🔍 First few lines of decoded key:"
          head -n 10 private.key
      
          echo "🔍 File size:"
          stat --format="%s bytes" private.key
      
          echo "🔍 Attempting import:"
          gpg --batch --import private.key

          echo "🔐 Export public key to file used by sign-file"
          # Export public and secret keys to files used by sign-file
          gpg --batch --yes --pinentry-mode loopback --passphrase=$GPG_PASSPHRASE \
              --export > signing_key.pub
              
          echo "🔐 Export private key to file used by sign-file"
          gpg --batch --yes --pinentry-mode loopback --passphrase=$GPG_PASSPHRASE \
              --export-secret-keys > signing_key.sec

          ls -l signing_key.pub signing_key.sec || echo "❌ Key files missing"

          pwd

          echo $HOME
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install build dependencies from control file
        run: |
          sudo apt-get update
          sudo apt-get install -y equivs devscripts
          mk-build-deps --install --root-cmd sudo --tool "apt-get -y" debian/control

      - name: Download and install dpkg-sig
        run: |
          wget http://ftp.de.debian.org/debian/pool/main/d/dpkg-sig/dpkg-sig_0.13.1+nmu4_all.deb
          sudo apt install ./dpkg-sig_0.13.1+nmu4_all.deb
          rm ./dpkg-sig_0.13.1+nmu4_all.deb

      - name: Build debian package
        run: debuild -us -uc -tc -b

      - name: Move .deb file locally
        run: mv ../*.deb ./

      - name: Sign the .deb file
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: dpkg-sig --sign builder --gpg-options "--batch --yes --passphrase=$GPG_PASSPHRASE --pinentry-mode loopback" ./*.deb

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gasket-deb-${{ github.run_number }}
          path: ./*.deb
