name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install debuild
        run: sudo apt-get update && sudo apt-get install -y devscripts
        
      - name: Build debian package
        run: debuild -us -uc -tc -b

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gasket-deb-${{ github.run_number }}
          path: ../*.deb
