name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
      - name: Decode and inspect GPG key
        run: |
          echo "$PRIVATE_GPG_KEY" | base64 --decode > private.key
      
          echo "🔍 First few lines of decoded key:"
          head -n 10 private.key
      
          echo "🔍 File size:"
          stat --format="%s bytes" private.key
      
          echo "🔍 GPG packet inspection:"
          gpg --batch --list-packets private.key || echo "⚠️ GPG packet inspection failed"
      
          echo "🔍 Attempting import:"
          gpg --batch --import private.key || echo "⚠️ GPG import failed"
      
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install build dependencies from control file
        run: |
          sudo apt-get update
          sudo apt-get install -y equivs devscripts
          mk-build-deps --install --root-cmd sudo --tool "apt-get -y" debian/control

      - name: Download and install dpkg-sig
        run: |
          wget http://ftp.de.debian.org/debian/pool/main/d/dpkg-sig/dpkg-sig_0.13.1+nmu4_all.deb
          sudo apt install ./dpkg-sig_0.13.1+nmu4_all.deb
          rm ./dpkg-sig_0.13.1+nmu4_all.deb

      - name: Build debian package
        run: debuild -us -uc -tc -b

      - name: Move .deb file locally
        run: mv ../*.deb ./

      - name: Sign the .deb file
        run: |
          dpkg-sig --sign builder ./*.deb

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gasket-deb-${{ github.run_number }}
          path: ./*.deb
